version: '3.8'

services:
  django:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=inkteo_db
      - DB_PORT=5432
    depends_on:
      - postgres
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
  media_volume: