version: '3.8'

services:
  web:
    build: .
    restart: always
    command: >
      bash -c "python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=False
      - SECRET_KEY=TKInkteo3506
      - ALLOWED_HOSTS=panel.inkteo.com,194.113.64.207,inkteo-inkteo.72xy9m.easypanel.host
      - DB_NAME=inkteo
      - DB_USER=postgres
      - DB_PASSWORD=Heysem35Saint!
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

  postgres:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=inkteo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Heysem35Saint!

volumes:
  postgres_data:
  static_volume:
  media_volume: